import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NotesProvider } from '@/context/NoteContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-950`}>
        <main className="flex gap-10 mt-10 text-neutral-300 w-full max-w-6xl m-auto">
          <NotesProvider>
            {children}
          </NotesProvider>
        </main>
      </body>
    </html>
  )
}
